### ISSUE TITLE
Can't get channels informations with files generated with DEWESoft X3

### ISSUE THREAD

**Issue by DaHelmut** [costerwi/dwdatareader#16]
With the latest versions of the [DWDataReaderLib](https://www.dewesoft.com/download?file=DWDataReader_v4_2_0_4___.zip) and a file generated with DEWESoft X3 SP2, the channels informations can be retrieved.

The new library adds one variable to the DWChannel structure which is "data_type".

The issue is corrected by changing the DWChannel _fields_ variable to : 

`    _fields_ = [("index", ctypes.c_int),
                ("_name", ctypes.c_char * 100),
                ("_unit", ctypes.c_char * 20),
                ("_description", ctypes.c_char * 200),
                ("color" , ctypes.c_uint),
                ("array_size", ctypes.c_int),
	        ("data_type", ctypes.c_int)]
`

**Comment by fleimgruber** [comment]
Thanks for the information! What you are suggesting has already been tried last year in https://github.com/costerwi/dwdatareader/pull/14 and the more recent https://github.com/costerwi/dwdatareader/pull/17 so will sooner or later make it into master. Stay tuned!

**Comment by costerwi** [comment]
Sorry I've been away from this. I just merged #17 . It would be interesting to know how it's working with the newer versions of the API library.
