### ISSUE TITLE
unittests in master fail

### ISSUE THREAD

**Issue by mafeko** [costerwi/dwdatareader#18]
Hi,

I'd like to understand how it is possible, that the current codebase in master isn't able to run all unittests successfully on Linux?
Is this system-related or are the tests deprecated?

Thank you.
Martin

**Comment by costerwi** [comment]
When I merged #10 it appeared that this would be a temporary problem but then I got busy with other things. I think the latest merge #17 should skip the tests that are known to fail. Perhaps the latest API library will enable that feature to work on Linux.
