### ISSUE TITLE
enhancement: get scaled data in batches

### ISSUE THREAD

**Issue by mafeko** [costerwi/dwdatareader#19]
In my usecase reading in a channel with +50million signals I sometimes face memory issues on the system the code is running.

An idea would be to offer this pagination with an offset and count in the `scaled` method like
```python
def scaled(self,offset:int, count:int):
```
so one channel could be read in a parallel distributed way.

**Comment by costerwi** [comment]
There is an existing method that I think can help with this problem `series_generator(chunk_size)` will allow you to iterate over a long channel in chunks. The usage is illustrated in #6
