### ISSUE TITLE
How to get the data?

### ISSUE THREAD

**Issue by lhx0525** [costerwi/dwdatareader#20]
I have been able to get the field names in the dxd file, how can I get the data in each field name?

**Comment by costerwi** [comment]
I assume you are referring to the channel names and channel data. Probably you are looking for the `DWChannel.series()` method. It returns a [Pandas Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) containing the data from the channel. For example:
```Python
import dwdatareader as dw
with dw.open('myfile.d7d') as f:
    print(f.info)
    data = f['chname1'].series()
    print(data.mean())
```
