### ISSUE TITLE
sub-level of variables cannot be accessed

### ISSUE THREAD

**Issue by stefise** [costerwi/dwdatareader#21]
First of all, thanks for this great library, it improved so many things for me.

I noticed I cannot access certain channels, e.g. when we do Flicker-measurements. The channels are called e.g. "I_Pst_L1", and in Dewesoft they have sub-variables with certain angles, e.g. 30°, 50°, ... 
When I manually export to csv in Dewesoft, those angles can be exported, while it seems to not be possible for the library / the dll.

![grafik](https://user-images.githubusercontent.com/58982633/71001055-c0565a00-20dc-11ea-8c54-f87da9aabaee.png)

Any experience with this, or even a way to do it?

Best, Stef

**Comment by costerwi** [comment]
Thanks, I'm glad it is useful.

I think what you have may be called an "array" or "axis" within the channel. Check this and see if it is greater than 1:
```python
with dw.open('myfile.d7d') as f:
    print(f['I_Pst_L1'].array_size)
```
Unfortunately, this module doesn't currently support channel arrays. The Dewesoft DLL documentation isn't very clear on how to use them. It looks like the string values are extracted individually with the call:
```c
DWStatus DWGetArrayIndexValue(int ch_index, int array_info_index, int array_value_index, char* value, int value_size);
```

**Comment by stefise** [comment]
Finally back at this, sorry for the delay.

It is as you said, return value is 4.

Wondering if there is something I can do to help implement this?

**Comment by costerwi** [comment]
Can you share a small example file? I will try to take a look.

**Comment by stefise** [comment]
Hi Carl,

I prepared a small test file, as attached. It includes the output csv file if I export the three channels I_Pst_L1 / L2 / L3

[dwdatareader_I_Pst_sample2.zip](https://github.com/costerwi/dwdatareader/files/4180264/dwdatareader_I_Pst_sample2.zip)

Hope this helps & thanks!
