### ISSUE TITLE
Update to new lib version 4.2.0.19

### ISSUE THREAD

**Issue by yellow-submarine-on-tour** [costerwi/dwdatareader#31]
Hi,

using the dwdatareader lib we ascertained two bugs in the DWDataReaderLib
- DWGetScaledSamplesCount() is zero when using big data file with asynchronous channels
- Wrong time values in files with lost data ('*.lost*.dxd')

We issued them and Dewesoft released a new version that solved those issues. Please update the repo with the newest files...

Thanks and best wishes

/chr

**Comment by costerwi** [comment]
Thanks. This should be done with with merge #33
