### ISSUE TITLE
Upgrade to latest dewesoft library

### ISSUE THREAD

**Issue by alexgordtop** [costerwi/dwdatareader#49]
Hi,
we're having trouble with older .dxd files, that can't be read with the current library.

Could you please upgrade to the new library provided by dewesoft?

https://developer.dewesoft.com/questions/issue-in-dwdatareader-version-4020021

Thanks in advance,
Alex

**Comment by costerwi** [comment]
Upgraded to latest library in #50 

Thanks

**Comment by alexgordtop** [comment]
Thanks!


_______________________________________________________
Alexander Gordt
Senior Software Architect

objective partner AG | Bergstr. 45/1 | 69469 Weinheim
M: +49 172 2931963 T: +49 172 2931963 | F: +49 6201 398612
E: ***@***.*** | W: https://www.objective-partner.de

Handelsregister Mannheim: HRB 700466 | Ust-ID Nr. DE173591044
Vorstand: Andreas Bader, Michael Thron | Vors. des Aufsichtsrates: Dr. Manfred Schneider
Näheres zur Informationspflicht nach Artikel 13 DS-GVO und zu unserer Verarbeitung Ihrer personenbezogenen Daten erfahren Sie hier https://www.objective-partner.de/datenschutz
_______________________________________________________


________________________________
Von: Carl Osterwisch ***@***.***>
Gesendet: Saturday, March 26, 2022 2:48:10 PM
An: costerwi/dwdatareader ***@***.***>
Cc: Alexander Gordt ***@***.***>; Author ***@***.***>
Betreff: Re: [costerwi/dwdatareader] Upgrade to latest dewesoft library (Issue #49)


Upgraded to latest library in #50<https://github.com/costerwi/dwdatareader/pull/50>

Thanks
