### ISSUE TITLE
Store trigger event information?

### ISSUE THREAD

**Issue by Phil-10107536** [costerwi/dwdatareader#55]
Looking through a bunch of Dewesoft data that was stored based on a trigger events.

Is there a way that I could read in the information that triggered the event for each file imported into Python? This would not include the "Storing started" or "Storing stopped", just the "Data trigger events" line

Was reading through the __init__.py to determine if I could get this information myself, however, it is above my current level of skill.

![image](https://user-images.githubusercontent.com/113722757/191617160-acda2f0f-51bc-4540-998f-9a9895f2bd5a.png)

**Comment by costerwi** [comment]
The documentation needs a lot of work.

You can get a Pandas data frame of all events with the method `events()`. The headings will be time (the index), type, and text. You could filter this to contain only trigger events using Pandas methods like this:
``` python
with dw.open('Example_Drive01.d7d') as d7d:
    all_events = d7d.events()
    
trigger_events = all_events[ all_events.text.str.contains('trigger') ]
```
