### ISSUE TITLE
DWError: error in DLL - from DewesoftX 23.01

### ISSUE THREAD

**Issue by je-bje** [costerwi/dwdatareader#57]
Hello, 

The DLL seems to be failing when updating to the latest release of DewesoftX, 2023.1.

> Traceback (most recent call last):
> 
>   File "C:\ProgramData\Anaconda\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
>     exec(code, globals, locals)
> 
>   File "c:\users\jesper\documents\python\projects\dewe_dyno\process_dxd.py", line 18, in <module>
>     fdw = dw.open("C:/Users/Public/Documents/Dewesoft/Data/12-01-2023/Run_08.dxd")
> 
>   File "C:\ProgramData\Anaconda\lib\site-packages\dwdatareader\__init__.py", line 538, in open
>     return DWFile(source)
> 
>   File "C:\ProgramData\Anaconda\lib\site-packages\dwdatareader\__init__.py", line 360, in __init__
>     self.open(source) # If this fails then the instance is not constructed
> 
>   File "C:\ProgramData\Anaconda\lib\site-packages\dwdatareader\__init__.py", line 390, in open
>     raise DWError(stat)
> 
> DWError: error in DLL

**Comment by costerwi** [comment]
Hopefully this is fixed. The dll has just been updated with #58

**Comment by je-bje** [comment]
Issue was fixed with latest update.
