### ISSUE TITLE
Feature Request: Present d7d file as generator object

### ISSUE THREAD

**Issue by fleimgruber** [costerwi/dwdatareader#6]
The `DWChannel.scaled()` function eagerly reads all channel data into a `pandas.Series`. For big `.d7d` files, this leads to `MemoryError`. I am not familiar with the `DWDataReaderLib64.dll`, but as a pure Python solution, one could present channel data as a generator, i.e. using `yield` for every measurement or chunk of measurements.

This would enable using the `.d7d` as a streaming source of data (e.g. to put into a data base or analyze on the fly). What do you think?

**Comment by costerwi** [comment]
Yes, the dll allows random access to the data so it should be possible to add access like this. I'll look into it.

I've read long channels. Your file must be immense! What line produces your MemoryError?

**Comment by fleimgruber** [comment]
I already prepared a patch for this, will open a pull request to discuss it later.

The file is about 2.7 GB in size and the `MemoryError` (depending on current system memory load) happens in line https://github.com/costerwi/dwdatareader/blob/master/dwdatareader/__init__.py#L105 (resp. https://github.com/costerwi/dwdatareader/blob/master/dwdatareader/__init__.py#L112)

``` python
import dwdatareader as dw

with dw.open('./data.d7d') as f:
    print(f.info)
```
```
2016-04-14 16:00:00.200788+00:00 20000.0 Hz 10799.9941 s
```

**Comment by fleimgruber** [comment]
See #7 for a possible solution.

From a user perspective, this enables consumption in a streaming fashion with a lower memory footprint, e.g.:
``` python
import dwdatareader as dw

with dw.open('myfile.d7d') as f:
    for chunk in f['chname1'].series_generator(1000)
        analyze_a_single(chunk)
```

**Comment by costerwi** [comment]
Thanks for your contribution!
