### ISSUE TITLE
How to extract "LP Filter" and "LP Filter data"?

### ISSUE THREAD

**Issue by jbebic** [costerwi/dwdatareader#60]
We are using your library to batch process recordings made by others and supplied to us as d7d files. For quality assurance purposes we are collecting and archiving the metadata of the recordings (example code included below). We can pull out most of what we need, but our client recently asked us to also capture the LP Filter and the LP Filter data fields. We can see these in [DevesoftX](https://dewesoft.com/download) but can’t find them in the data structures available under `fh` below.
 
```python
import dwdatareader as dw # from https://github.com/costerwi/dwdatareader
 
fh = dw.open(fname)
my_channels_info = [] # empty list to hold the signals info
for ch in fh.values():
      hkeys = fh.header.keys()
      customer = fh.header['CUSTOMER'] if 'CUSTOMER' in hkeys else 'unknown customer'
      testnum = fh.header['TESTNUMBER'] if 'TESTNUMBER’ in hkeys else 'undefined'
      row = {'name': ch.name, # these are added into a summary dataframe later.
            'unit': ch.unit,
            'desc': ch.description,
            'nsam': ch.number_of_samples,
            'customer': customer,
            'testnum': testnum,
            't_start': fh.info.start_store_time,
            'rate': fh.info.sample_rate,
            'duration': fh.info.duration,
            'fname': raw_fname
      }
      my_channels_info.append(row)
 
# transfer channels info into a dataframe
df1ch = pd.DataFrame(my_channels_info)
```
Here is the pertinent screen shot from DewesoftX
![image](https://user-images.githubusercontent.com/18373202/231190339-6193616a-b484-4dd0-81b4-83bd93f41642.png)

What we need is the stuff that opens to the right when hovering over these cells. Any guidance you can offer is welcome.  
Thanks in advance!

**Comment by jbebic** [comment]
A related extra question is: **Where to find the Sampling rate specific to a channel?**
We have a file with signals captured at two sample rates: 
  1. 40000s/sec (from analog inputs) and 
  2. 77.4 s/sec (from CAN). 

We can find the 40000 value under `fh.info.sample_rate`, but this pertains to the file, not the channel.

We thought we could derive it by taking: `1/(fh.info.duration/ch.number_of_samples)` but this yields an answer different from what is reported in DewesoftX; likely due to the variability in the CAN timing.  
Is by-channel sampling rate available anywhere?

**Comment by costerwi** [comment]
I'm glad this is useful for you. Unfortunately, I don't see anything in the Dewesoft documentation of their shared library (on which this interface is built) which mentions filters.

Similarly, the Channel info reported by their library does not contain the channel sampling frequency. Variable timing may be a problem but you might infer the channel sampling frequency from the sampling period like this:
``` python
for ch in fh.values():
    chData = ch.sampled()
    frequency = 1/(chData.index[1] - chData.index[0])
```
You could request enhancements like this from [Dewesoft](https://developer.dewesoft.com) and then I'm happy to add interfaces for this library.

**Comment by jbebic** [comment]
Thank you for the fast response! I posed the same question(s) to Dewesoft support, we will see if they reply. If you wish to track it on that side, my ticket is under this link: https://support.dewesoft.com/en/support/tickets/90199.
Best, Jovan
