### ISSUE TITLE
.dxd files generated with new Dewesoft release could not be opened

### ISSUE THREAD

**Issue by andornemeth** [costerwi/dwdatareader#62]
.dxd files generated with new Dewesoft release (2023.4 RELEASE-230724) could not be opened with dwdatareader: "DWError: d7d file corrupt".

Since 8/31/2023 there is a new v4_2_0_25 Dewesoft Data Reader Library: https://downloads.dewesoft.com/developers/DWDataReader.zip 
The .so and DLL files should be updated to the newest version. Hopefully, this will fix the issue.

Thank you in advance.

**Comment by costerwi** [comment]
The new Dewesoft library is now in the latest release 0.15.4 #63

I hope this will fix the issue!
Carl
