### ISSUE TITLE
Dewesoft library should be updated to the latest version

### ISSUE THREAD

**Issue by andornemeth** [costerwi/dwdatareader#65]
Dewesoft Data Reader Library should be updated to the latest version. 

Direct link: https://downloads.dewesoft.com/developers/DWDataReader.zip

The current available version is: [v4_2_0_31] - 2024-06-28
(https://dewesoft.com/download/developer-downloads -> Dewesoft Data Reader Library -> Changelog)

**Comment by costerwi** [comment]
Closing with release 0.15.5
https://github.com/costerwi/dwdatareader/releases/tag/v0.15.5
